version = 0.1

[default.global.parameters]
region = "<aws_region>"
profile = "default"

[production.deploy.parameters]
stack_name = "<stack_name>"
s3_bucket = "<cloudformation_artifact_bucket>"
capabilities = ["CAPABILITY_NAMED_IAM"]
parameter_overrides = ["<parameter_name>=<parameter_value>"]

[development.deploy.parameters]
stack_name = "<stack_name>"
s3_bucket = "<cloudformation_artifact_bucket>"
capabilities = ["CAPABILITY_NAMED_IAM"]
parameter_overrides = ["<parameter_name>=<parameter_value>"]
