name: Python packages
on: [push]
env:
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  AWS_DEFAULT_REGION: us-east-1
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'
      - run: pip3 install -r requirements.txt
      - run: ./bin/run_unit_tests
      - uses: coverallsapp/github-action@v2