name: Python packages
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'
      - run: pip3 install -r requirements.txt
      - run: ./bin/run_unit_tests
